### ISSUE TITLE
"redirected you too many times" in iframe tag

### ISSUE THREAD

**Issue by akhila45** [webodf/ViewerJS#282]
Hello,
   ViewerJs 0.5.8 is not loading in live server iframe. The only error its showing on the empty page is "redirected you too many times." what is the fix for this? Can someone help me. Thanks in advance.

**Comment by thz** [comment]
This is actually not a support channel. But perhaps you can have a minimized reproduction of the issue online somewhere and link it here? That way we might spot an issue in viewerjs itself.

**Comment by akhila45** [comment]
test

**Comment by akhila45** [comment]
Hello,

  I have tried with another live server, there it is working  and the only place in live server it doesnot work. I have attached screenshot. Please check

 

Thanks,

Akhila
